### PR TITLE
chore: remove redundant compositions + fix local:docker ones

### LINKED ISSUE #171: Running the example in the readme fails
after setting up testground, when running the example in the README.md on `main`, 

`testground run composition -f compositions/local-docker/big-blocks/001-val-large-txs-3.toml --wait`

we get this failure from all three validators
```
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/testground/sdk-go/run.HandlePanics()
	/go/pkg/mod/github.com/testground/sdk-go@v0.3.0/run/panic.go:23 +0x39
panic({0x2c3b5a0, 0xc003314000})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/celestiaorg/test-infra/tests/helpers/common.GetRandomisedPeers(0x1, 0x3, {0xc000511090, 0x2, 0x2})
	/plan/tests/helpers/common/validator.go:254 +0x1a5
github.com/celestiaorg/test-infra/tests/helpers/common.BuildValidator({0x3c31ed0, 0xc0005620c0}, 0xc00103d200, 0xc00025e4b0, {0x0?, 0x0, 0x0?})
	/plan/tests/helpers/common/validator.go:234 +0x15a6
github.com/celestiaorg/test-infra/tests/helpers/app-sync.RunValidator(0xc00103d200, 0xc00025e4b0)
	/plan/tests/helpers/app-sync/run_validator.go:52 +0x35f
github.com/celestiaorg/test-infra/tests/plans/big-blocks.ValSubmitLargeTxs(0xc00103d200, 0xc00025e4b0)
	/plan/tests/plans/big-blocks/tc-001-val-large-txs.go:16 +0x85
github.com/testground/sdk-go/run.invoke.func4()
	/go/pkg/mod/github.com/testground/sdk-go@v0.3.0/run/invoker.go:173 +0x142
created by github.com/testground/sdk-go/run.invoke
	/go/pkg/mod/github.com/testground/sdk-go@v0.3.0/run/invoker.go:162 +0x78c
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/testground/sdk-go/runtime.(*RunEnv).RecordCrash(0xc00103d200, {0x28a1ce0?, 0xc0028e60f0?})
	/go/pkg/mod/github.com/testground/sdk-go@v0.3.0/runtime/runenv_events.go:246 +0x7b
github.com/testground/sdk-go/run.invoke(0xc00103d200, {0x291a720?, 0x376ddd0})
	/go/pkg/mod/github.com/testground/sdk-go@v0.3.0/run/invoker.go:190 +0x8e5
github.com/testground/sdk-go/run.InvokeMap(0xc000006340?)
	/go/pkg/mod/github.com/testground/sdk-go@v0.3.0/run/invoker.go:77 +0x94
main.main()
	/plan/main.go:30 +0x25
```

### PR DESCRIPTION
**Pull request by Bidon15**
## Overview

Closes #171 

In addition, I removed the 32 sq sz to prepare for 128 or 256 instead

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

File: tests/helpers/common/bridge.go [hunk 1]
```diff
@@ -51,9 +51,12 @@ func BuildBridge(ctx context.Context, runenv *runtime.RunEnv, initCtx *run.InitC
 	cfg.Gateway.Enabled = true
 	cfg.Gateway.Port = "26659"
 
-	optlOpts := []otlpmetrichttp.Option{
-		otlpmetrichttp.WithEndpoint(runenv.StringParam("otel-collector-address")),
-		otlpmetrichttp.WithInsecure(),
+	var optlOpts []otlpmetrichttp.Option
+	if runenv.StringParam("otel-collector-address") != "" {
```
Comment (Bidon15) [inline tests/helpers/common/bridge.go:55]: this will be transfered as a separate issue to solve
Idea: we will include metrics as a standard node init (good first issue)

Comment (Bidon15) [reply tests/helpers/common/bridge.go:55]: will be fixed by #178

File: compositions/local-docker/big-blocks/002-da-sync-12.toml [hunk 2]
```diff
@@ -5,21 +5,44 @@
 [global]
   plan = "celestia"
   case = "002-da-sync"
-  total_instances = 12
+  total_instances = 13
```
Comment (jrmanes) [inline compositions/local-docker/big-blocks/002-da-sync-12.toml:8]: with this changed, is the file name still valid?, or now should be:
```
compositions/local-docker/big-blocks/002-da-sync-13.toml
```

File: compositions/local-docker/big-blocks/003-full-sync-past-12.toml [hunk 3]
```diff
@@ -5,21 +5,44 @@
 [global]
   plan = "celestia"
   case = "003-full-sync-past"
-  total_instances = 12
+  total_instances = 13
```
Comment (jrmanes) [inline compositions/local-docker/big-blocks/003-full-sync-past-12.toml:8]: same here, is the file name still ok?

File: compositions/local-docker/big-blocks/004-full-light-past-12.toml [hunk 4]
```diff
@@ -5,21 +5,44 @@
 [global]
   plan = "celestia"
   case = "004-full-light-past"
-  total_instances = 12
+  total_instances = 13
```
Comment (jrmanes) [inline compositions/local-docker/big-blocks/004-full-light-past-12.toml:8]: same here, is the file name still ok?

**Review by jrmanes — APPROVED** [review]
apart from the file names, LGTM 🚀 
great job!
